[2019-11-16 19:29:06,491] [LinqHelper.py:52] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 19:30:33,416] [LinqHelper.py:52] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 19:35:41,607] [LinqHelper.py:52] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 19:36:21,333] [LinqHelper.py:55] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 19:36:33,249] [LinqHelper.py:56] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 19:38:16,042] [LinqHelper.py:56] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 19:53:01,518] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: count, created_time, id, login_phone, password, updated_time, vername
[2019-11-16 19:55:30,727] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: created_time, id, login_phone, password, vername
[2019-11-16 19:56:29,802] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: created_time, id, login_phone, password, vername
[2019-11-16 19:58:18,773] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: created_time, id, login_phone, password, vername
[2019-11-16 19:58:53,991] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: created_time, id, login_phone, password, vername
[2019-11-16 20:01:25,449] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: created_time, id, login_phone, password, vername
[2019-11-16 20:01:30,007] [LinqHelper.py:57] [LinqHelper:db_find] [ERROR]- 请求出错：Cannot resolve keyword 'phone' into field. Choices are: created_time, id, login_phone, password, vername
[2019-11-16 20:03:15,622] [LinqHelper.py:52] [LinqHelper:db_find] [ERROR]- 请求出错：没有找到该用户
[2019-11-16 20:03:15,623] [views.py:44] [views:post] [ERROR]- 添加失败：(1048, "Column 'vername' cannot be null")
[2019-11-16 20:03:42,011] [views.py:44] [views:post] [ERROR]- 添加失败：(1048, "Column 'vername' cannot be null")
